# Generated by Django 4.0 on 2024-03-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Widget_Mapping',
            fields=[
                ('mapping_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('page_id', models.CharField(max_length=100)),
                ('widget_id', models.CharField(max_length=255)),
                ('page_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50)),
                ('report_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_by', models.IntegerField()),
                ('created_dt', models.DateTimeField()),
                ('updated_by', models.IntegerField()),
                ('update_dt', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('is_deleted', models.CharField(default='N', max_length=2)),
                ('container_id', models.IntegerField()),
                ('import_from_report_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Feature_Page',
            fields=[
                ('feature_page_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=25)),
                ('definition', models.JSONField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_by', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
                ('container_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100)),
                ('report_id', models.CharField(max_length=100)),
                ('page_name', models.CharField(max_length=100)),
                ('page_order', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('definition', models.JSONField()),
                ('created_by', models.IntegerField()),
                ('created_dt', models.DateTimeField()),
                ('updated_by', models.IntegerField()),
                ('update_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('widget_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('widget_name', models.CharField(max_length=100)),
                ('definition', models.JSONField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('container_id', models.IntegerField()),
                ('is_shared', models.CharField(max_length=255)),
                ('is_deleted', models.CharField(max_length=255)),
            ],
        ),
    ]
