# Generated by Django 4.0 on 2024-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
    ]
