# Generated by Django 4.0 on 2024-03-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_report_created_by_alter_report_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='update_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
