# Generated by Django 4.0 on 2024-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_report_created_dt_alter_report_update_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='is_deleted',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='widget',
            name='is_shared',
            field=models.CharField(max_length=2),
        ),
    ]
